#!/usr/bin/env bash

function do_stow {
    pushd $1

    for PCK in */
    do
        PCK=${PCK%/}
        echo "stow -R $PCK"
        stow --ignore='README.*' -t $HOME -R $PCK
    done

    popd
}

do_stow $HOME/.dotfiles/stow
do_stow $HOME/.dotfiles/personal
